
-- \COPY tbl_trade_order TO '/home/postgres/tbl_trade_order.csv' (FORMAT csv, DELIMITER ',', HEADER true);

-- 用作数据量测试

INSERT INTO tbl_trade_order("id",
                            "serverId",
                            "orderId",
                            "symbol",
                            "account",
                            "type",
                            "status",
                            "submitTime",
                            "closeTime",
                            "acceptTime",
                            "createTime",
                            "orderVolumn",
                            "dealVolumn",
                            "orderPrice",
                            "orderType",
                            "nTime",
                            "tag",
                            "risker",
                            "timeout",
                            "force",
                            "dealPrice",
                            "errCode",
                            "errDetail",
                            "DRI")
                     SELECT n::varchar(32),
                            n,
                            n,
                            n||'.SH',
                            n,
                            1,
                            n / 1000,
                            now()::varchar(32),
                            now()::varchar(32),
                            now()::varchar(32),
                            now()::varchar(32),
                            n,
                            n,
                            n,
                            n / 1000,
                            n,
                            'tag1',
                            'risker2',
                            n,
                            true,
                            n,
                            'this is an error code',
                            'column  of relation  does not exist',
                            n||'.DRI'
                     FROM generate_series(1,10) n;